name: form_elements
description: Reusable web components for forms
author: Gulshan Singh <gsingh2011@gmail.com>
homepage: https://github.com/gsingh93/polymer-form-elements
version: "1.1.0"
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  sprintf: '>=1.0.8 <2.0.0'
  polymer: '>=0.12.0 <0.13.0'
